### ISSUE TITLE
BOTIUM_DIRECTLINE3_SECRET

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-connector-directline3#14]
Please give us example on how to add BOTIUM_DIRECTLINE3_SECRET in .env file for Botium.
Also in .env file what we can add else

**Comment by codeforequity-at** [comment]
You can find generic instructions from where Botium loads capabilities here:
https://github.com/codeforequity-at/botium-core/wiki/Botium-Configuration#configuration-source

Typically, main configuration is done in botium.json file, and sensitive information is handed over with environment variables.
