### ISSUE TITLE
Support for click on Adaptive Cards,Decision making buttons

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-connector-directline3#15]
Using DirectLine3:
1.We need to perform click action on adaptive card and verify for Bot response.
2. Decision making buttons as "You are correct" and "You can improve" these are buttons in the chatwindow and i need to click on "You are correct" button to verify response.
What is the approach available.

![image](https://user-images.githubusercontent.com/30192609/56424314-57a8aa80-62cd-11e9-94bd-dfce12f87531.png)

**Comment by codeforequity-at** [comment]
You can find samples for simulating button clicks and form input in the samples folder of this repository.

**Comment by vijaysimh** [comment]
Hello Thanks for adding Adaptive Card convo.txt .As i observed botium team have provided support for Column action with buttons.But as the scenario seems to be within Cards.Please find the detailed LOG with screenshot attached for reference .

adaptive

#me
BUTTON card bingsports

#bot
Welcome to Mockbot v4!

#bot
BUTTONS Column action --This works fine for buttons

As per the below screenshot attached it takes Cards as the parameter and within that Delete PO. 
,Close PO are the actions ,which is not ideally of type BUTTON.Hence test cases fails.
Please provide solution for bot response: as below

![image](https://user-images.githubusercontent.com/30192609/58363867-cf6b8580-7ec8-11e9-884e-ffbf852336f8.png)
VERBOSE LOG ATTACHED:

 "type": "Container",
  botium-Convo               "items": [
  botium-Convo                 {
  botium-Convo                   "type": "ColumnSet",
  botium-Convo                   "**columns**": [
  botium-Convo                     {
  botium-Convo                       "type": "Column",
  botium-Convo                       "width": "stretch",
  botium-Convo                       "items": [
  botium-Convo                         {
  botium-Convo                           "type": "TextBlock",
  botium-Convo                           "text": "Delete PO",
  botium-Convo                           "spacing": "none",
  botium-Convo                           "separation": "none",
  botium-Convo                           "height": "stretch"
  botium-Convo                         }
  botium-Convo                       ],
  botium-Convo                       "selectAction": {
  botium-Convo                         "type": "Action.Submit",
  botium-Convo                         "data": {
  botium-Convo                           "value": "Delete PO",
  botium-Convo                           "text": "Delete PO"
  botium-Convo                         },
  botium-Convo                         "title": "Delete PO"
  botium-Convo                       }
  botium-Convo                     },
  botium-Convo                     {
  botium-Convo                       "type": "Column",
  botium-Convo                       "width": "stretch",
  botium-Convo                       "items": [
  botium-Convo                         {
  botium-Convo                           "type": "TextBlock",
  botium-Convo                           "text": "Close PO",
  botium-Convo                           "height": "stretch"
  botium-Convo                         }
  botium-Convo                       ],
  botium-Convo                       "selectAction": {
  botium-Convo                         "type": "Action.Submit",
  botium-Convo                         "data": {
  botium-Convo                           "value": "Close PO",
  botium-Convo                           "text": "Close PO"
  botium-Convo                         },
  botium-Convo                         "title": "Close PO"
  botium-Convo                       }
  botium-Convo                     }
  botium-Convo                   ]
  botium-Convo                 }
  botium-Convo               ]
  botium-Convo             }
  botium-Convo           ]
  botium-Convo         }
  botium-Convo       }
  botium-Convo     ],
  botium-Convo     "replyToId": "XXXXXXXXXXXX-k|0000000"
  botium-Convo   },
  botium-Convo   "media": [],
  botium-Convo   "buttons": [],
  botium-Convo   "cards": [
  botium-Convo     {
  botium-Convo       "text": [
  botium-Convo         "Do you want to delete purchase order permanently from XXX? \r\n or \r\n Do you want to close YYY?",
  botium-Convo         "Delete PO",
  botium-Convo         "Close PO"
  botium-Convo       ],
  botium-Convo       "image": false
  botium-Convo     }


#me
BUTTON Column action Delete PO --Tried in this way for Delete PO utterance(Here BUTTON->CARD must be changed)

**Comment by codeforequity-at** [comment]
1. Did you use the latest directline connector build for your test ? The handling of cards is currently solved by using the first text block in the card for the assertions by default. With the latest build of the connector, the button actions should have been recognized.

2. What directline event a button click simulation is actually mapped to is a matter of configuration. The click simulation is completely independent if the response & assertion section. Depending on how your directline chatbot is implemented, a button click maybe be sent as "event" or as some custom activity or just as plain text.
