### ISSUE TITLE
Botium timeout capability directline3

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-connector-directline3#19]
Hi 
Please let us know by executing the below command am facing the 60000ms asysnc error.

Workaround :whether there is any Botium capability called BOTIUM_TIMEOUT which resolves the below error which i have posted.

C:\Users\\workspace>botium-cli run mochawesome --convos=./spec/convo --config=./spec/botium.json

  Botium Test-Suite
    1) DashboardUtt-A2/HELLO_UTT-L1
    2) DashboardUtt-A2/HELLO_UTT-L2

  0 passing (2m)
  2 failing

  1) Botium Test-Suite
       HelloWorldUtt-A2/HELLO_UTT-L1:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by alopix** [comment]
Not part of the official botium/codeforequity team but you should probably post this on the main repo as instructed [here](https://github.com/codeforequity-at/botium-connector-directline3/issues/3)

**Comment by codeforequity-at** [comment]
@vijaysimh please use the main support forum for questions.

Hitting the timeout of 60 seconds usually means that there is something wrong with the Directline connection - or is it reasonable to assume that the bot you are testing needs more time than 60 seconds for a response ?

**Comment by vijaysimh** [comment]
Timeout of 60 seconds was resolved by whitelisting from antivirus firewall.
Its connecting.

With Regards

Vijaysimha N

7760084921
