### ISSUE TITLE
Adaptive Card

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-connector-directline3#24]
ADAPTIVE CARDS(directline3), please illustrate the same example in excel format 

card

#me
BUTTON thumbnailcard

#bot
Welcome to Mockbot v4!

#bot
Microsoft Surface Pro
MEDIA surface1.jpg

**Comment by codeforequity-at** [comment]
You can use the same constructs in Excel as in Text format.

![image](https://user-images.githubusercontent.com/26287439/58289508-ee79f280-7db6-11e9-9595-da9379671c1d.png)
