### ISSUE TITLE
Unable to run the directline3

### ISSUE THREAD

**Issue by nidhi-m25** [codeforequity-at/botium-connector-directline3#27]
When trying to run the 'npm install' command on package.json. 
Below error comes-> 
`npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent /*git path over here*/ ls-remote -h -t https://github.com/codeforequity-at/jsonpath.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent`

Note- Git is already installed and git path is set properly.

**Comment by codeforequity-at** [comment]
It seems as if there is no git client installled ?
