### ISSUE TITLE
Unable to identify button click and card using directline 3

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-connector-directline3#32]
Hi,

I am using botium-cli version :0.0.56 and botium-directline3 version: 0.0.15. Still when I execute  >botium-cli emulator browser 
to save convo files, it does not identify button click.
On button click, it shows {"val":"ShowBalance"}. and does not give proper bot response.
Please help and let me know if I am using best connector for creating chatbot script using events like button click and form submit.

**Comment by codeforequity-at** [comment]
the browser emulator in the botium-cli is outdated and won't be updated anymore, for the favour of the live chat in Botium Box. It will be removed from botium-cli very soon.
