### ISSUE TITLE
Cannot Run the botium through botium cli or botium binding

### ISSUE THREAD

**Issue by aaa-Mierzhate** [codeforequity-at/botium-connector-directline3#33]
When I ran through cli, i got error:
![image](https://user-images.githubusercontent.com/42384722/67049718-ce432b00-f0eb-11e9-9275-b2d3f409e07b.png)
When I ran through botium binding, i got error:
![image](https://user-images.githubusercontent.com/42384722/67051681-9e4a5680-f0f0-11e9-8b55-8da59a737fcc.png)

I used the botium-sample-eclipse, changed all the watson var to directline 3 :
botium.json 
![image](https://user-images.githubusercontent.com/42384722/67049984-51648100-f0ec-11e9-8de6-728a5dee250a.png)
package.json
![image](https://user-images.githubusercontent.com/42384722/67050009-617c6080-f0ec-11e9-84bc-72a604510efc.png)

**Comment by codeforequity-at** [comment]
In the first screenshot there is an error message coming from directline, "failed to connect". So this might be a firewall issue.

**Comment by codeforequity-at** [comment]
solved ?

**Comment by aaa-Mierzhate** [comment]
Yeah, Issue solved, because of the incorrect dircetline3 secret, thank you.
