### ISSUE TITLE
Gettig timeout error

### ISSUE THREAD

**Issue by anshikarathi** [codeforequity-at/botium-connector-directline3#5]
botium-BaseContainer WaitBotSays error Error: Queue.pop timeout after 10000

Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\javascript_wo
rspace\Ginger_chatbot\spec\botium.spec.js)

Getting timeout error 
running with mocha , tried using mocha --timeout 500000, but doesnt work
Please suggest something

**Comment by codeforequity-at** [comment]
pls use stackoverflow for questions.
