### ISSUE TITLE
Request for Suggestion

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-connector-directline3#9]
Hi 
I have configued for directLine3 connection via azure portal and post executing "mochawesome" command from cmd - TC_01.convo.txt file am getting "#Bot and the #me" reversed please let me know why.

**Below is the report generated from mochawesome:**

#bot: Hello, how may i help you
#bot: Purchase Order
#me: Hi

**Below is the convo.txt :**
TC_01

#me
Hi

#bot default
Hello, how may i help you

#bot default
Purchase Order

**Comment by codeforequity-at** [comment]
What version are you using ? We had similar issues which we were able to fix in the latest build.

**Comment by vijaysimh** [comment]
Botium version:
  "name": "botium-connector-directline3",
  "version": "0.0.8"

**Comment by vijaysimh** [comment]
In mochawesome report I need to customize the html report generated by running command:
botium-cli run mochawesome

As per my client input needs to make following changes in the generated mochawesome report(
/spec/convo/mochawesome-report/mochawesome.html)
**Pictorial representations:**
**Pie chart**  - Pass and fail percentage of utterance against _Bot_ response.
**Bar graph** - No of utterances executed and for the each utterance which is the respective _Intent_ matched
We need to customize the html report generated .Please suggest on how to proceed further and what changes need to be done.

**Comment by codeforequity-at** [comment]
try version 0.0.9
mochawesome report has no extension points. you would probably have to fork the project and add your changes.
